name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  eslint:
    name: Linting # job name (unique id)
    runs-on: ubuntu-latest # on which machine to run
    steps: # list of steps
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 21

      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: .

      - name: Install Dependencies
        run: npm ci

      - name: Code Linting
        run: npm run lint
